apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-backend
  labels:
    app: finance-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-backend
  template:
    metadata:
      labels:
        app: finance-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/keerthana-rajamani/finanace-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://finance-mysql:3306/financedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: finance-db-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finance-db-secret
              key: password
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: finance-backend
spec:
  selector:
    app: finance-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-frontend
  labels:
    app: finance-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-frontend
  template:
    metadata:
      labels:
        app: finance-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/keerthana-rajamani/finanace-frontend:latest
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: finance-frontend
spec:
  selector:
    app: finance-frontend
  ports:
  - port: 8081
    targetPort: 8081
  type: LoadBalancer
