spring.datasource.url=jdbc:mysql://localhost:3306/financedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

jwt.secret=finance_secret_key_256bit_minimum_length_required_here
jwt.expiration=28800000

gemini.api.key=AIzaSyDemoKeyReplaceWithYourActualGeminiAPIKey
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
